language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ttfreeman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ttfreeman/react-test npm test

after_success:
  - docker build -t ttfreeman/multi-client ./client
  - docker build -t ttfreeman/multi-nginx ./nginx
  - docker build -t ttfreeman/multi-server ./server
  - docker build -t ttfreeman/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all the production images above and push them to docker hub
  - docker push ttfreeman/multi-client
  - docker push ttfreeman/multi-nginx
  - docker push ttfreeman/multi-server
  - docker push ttfreeman/multi-worker

deploy:
  provider: elasticbeanstalk
  region:  us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-662292712255
  bucket_path: multi-docker
  on: 
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  
 